[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-mongodb-extensions"
version = "0.3.0.dev0"
description = "Extensions for Django MongoDB Backend"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.12"

[project.optional-dependencies]
mql_panel = [
    "django-debug-toolbar>=4.0",
]
rest_framework = [
    "djangorestframework>=3.14",
]

[dependency-groups]
docs = [
    "django>=4.2",
    "furo",
    "sphinx>=7",
    "sphinx-copybutton",
]
test = [
    "coverage",
    "django-mongodb-backend>=6.0",
    "django-mongodb-extensions[mql_panel,rest_framework]",
]

[project.urls]
Documentation = "https://django-mongodb-extensions.readthedocs.io"
Source = "https://github.com/mongodb-labs/django-mongodb-extensions"
Tracker = "https://github.com/mongodb-labs/django-mongodb-extensions/issues"

[tool.ruff.lint]
select = ["I", "F"]
